### ISSUE TITLE
Release version for Neos 5

### ISSUE THREAD

**Issue by simonschaufi** [die-wegmeister/Wegmeister.DatabaseStorage#16]
This package is not compatible with Neos 5 and neos/form 5.0. Please make it compatible. Thank you!

**Comment by Benjamin-K** [comment]
Hello @simonschaufi,

thanks for your request. I will update this package as soon as possible, but i need to finish some other tasks first. If you need this package to be compatible with Neos 5 and neos/form 5.0 and need in right now, consider forking this package and create a pull request with the required changes. Maybe you only need to update the composer dependencies, but one has to check that. 
I will be able to update this package in the middle of march, because i need to finish an important project first.

Greetings,
Benjamin
